// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAem3wRV02Rc6f9YlJ6fDHtyuukNzc8lis',
    appId: '1:7975052123:web:b8e5fe03d1dc3b9b5bf07e',
    messagingSenderId: '7975052123',
    projectId: 'meeting-app-3e422',
    authDomain: 'meeting-app-3e422.firebaseapp.com',
    storageBucket: 'meeting-app-3e422.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBY38wmqF4ZGv9HXOQq-T59PySO1txvlFo',
    appId: '1:7975052123:android:628bf1e701363d3e5bf07e',
    messagingSenderId: '7975052123',
    projectId: 'meeting-app-3e422',
    storageBucket: 'meeting-app-3e422.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4fQOmu1pT0xuknZdu21kYi-JhF8EHXMw',
    appId: '1:7975052123:ios:7ff9aa18d3e6d91e5bf07e',
    messagingSenderId: '7975052123',
    projectId: 'meeting-app-3e422',
    storageBucket: 'meeting-app-3e422.firebasestorage.app',
    androidClientId: '7975052123-19t69soov4262fajmpjq6lae9fqp3qrg.apps.googleusercontent.com',
    iosClientId: '7975052123-cpkj838iedg1e3kc38g1ho8ai4notafu.apps.googleusercontent.com',
    iosBundleId: 'com.example.meetingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4fQOmu1pT0xuknZdu21kYi-JhF8EHXMw',
    appId: '1:7975052123:ios:7ff9aa18d3e6d91e5bf07e',
    messagingSenderId: '7975052123',
    projectId: 'meeting-app-3e422',
    storageBucket: 'meeting-app-3e422.firebasestorage.app',
    androidClientId: '7975052123-19t69soov4262fajmpjq6lae9fqp3qrg.apps.googleusercontent.com',
    iosClientId: '7975052123-cpkj838iedg1e3kc38g1ho8ai4notafu.apps.googleusercontent.com',
    iosBundleId: 'com.example.meetingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAem3wRV02Rc6f9YlJ6fDHtyuukNzc8lis',
    appId: '1:7975052123:web:fecf14adfb4e9dc95bf07e',
    messagingSenderId: '7975052123',
    projectId: 'meeting-app-3e422',
    authDomain: 'meeting-app-3e422.firebaseapp.com',
    storageBucket: 'meeting-app-3e422.firebasestorage.app',
  );

}